spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1f3g3w7ongo10d35o.mysql.rds.aliyuncs.com:3306/testdb
    password: zyj@123456
    username: zhongyejun
  main:
    allow-bean-definition-overriding: true

swagger:
  is:
    enable: true
  auth:
    server: http://localhost:8080/oauth/token?username=test&password=passwd&scope=all&grant_type=password
  service:
    name:

wx:
  app-id: wxc0caeb551cbd8e2f
  secret: 93a5ba0e7dff6908835c6f3ea4b1a3b5

api:
  boot:
    oauth:
      jwt:
        enable: true
      away: jdbc
    security:
      away: jdbc
      enable-default-store-delegate: false
      auth-prefix: /api/**,/users/**,/demo/**
      ignoring-urls:
